# Generated by Django 5.2.13 on 2026-04-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_assigned_centre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("coreadmin", "Core Admin"),
                    ("centreadmin", "Centre Admin"),
                    ("operator", "Operator"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
