# Generated by Django 5.2.13 on 2026-04-17 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("centre_name", models.CharField(max_length=100)),
                ("centre_address", models.TextField(blank=True, null=True)),
                ("centre_state", models.CharField(default="Delhi", max_length=100)),
                (
                    "centre_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "centre_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("centre_desc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("A", "A - Long Term >500hrs"),
                            ("B", "B - Short Term 91-500hrs"),
                            ("C", "C - Digital Competency ≤90hrs"),
                            ("D", "D - NIELIT DLC Courses"),
                            ("E", "E - NIELIT DLC Exams"),
                            ("F", "F - Summer Training"),
                            ("G", "G - Workshop"),
                            ("H", "H - NSQF"),
                            ("I", "I - Non-NSQF"),
                        ],
                        max_length=1,
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("course_category_desc", models.TextField(blank=True, null=True)),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=300)),
                ("course_desc", models.TextField(blank=True, null=True)),
                ("duration_hours", models.IntegerField(blank=True, null=True)),
                (
                    "course_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OnCampus", "On Campus"),
                            ("OffCampus", "Off Campus"),
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                            ("Hybrid", "Hybrid"),
                            ("Suspended", "Suspended"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "course_scheme",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "course_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("COMPLETED", "Completed"),
                            ("UPCOMING", "Upcoming"),
                            ("CANCELLED", "Cancelled"),
                            ("HOLD", "Hold"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.centre",
                    ),
                ),
                (
                    "course_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="core.coursecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "registration_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("candidate_name", models.CharField(max_length=200)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OBC", "OBC"),
                        ],
                        default="GEN",
                        max_length=10,
                    ),
                ),
                ("is_pwd", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "id_card_type",
                    models.CharField(default="Aadhaar Card", max_length=50),
                ),
                ("id_card_number", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email_id", models.EmailField(blank=True, max_length=200, null=True)),
                ("qualification", models.TextField(blank=True, null=True)),
                (
                    "course_applied",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "application_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "fee_reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_criteria",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("application_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["candidate_name"], name="core_studen_candida_086133_idx"
                    ),
                    models.Index(
                        fields=["application_number"],
                        name="core_studen_applica_6781c5_idx",
                    ),
                    models.Index(
                        fields=["mobile_number"], name="core_studen_mobile__c0cb0b_idx"
                    ),
                    models.Index(
                        fields=["email_id"], name="core_studen_email_i_5a6139_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(blank=True, max_length=200, null=True)),
                ("batch_start_date", models.DateField(blank=True, null=True)),
                ("batch_end_date", models.DateField(blank=True, null=True)),
                ("is_enrolled", models.BooleanField(default=False)),
                ("enrolled_date", models.DateField(blank=True, null=True)),
                ("is_trained", models.BooleanField(default=False)),
                ("trained_date", models.DateField(blank=True, null=True)),
                ("is_certified", models.BooleanField(default=False)),
                ("certified_date", models.DateField(blank=True, null=True)),
                ("is_placed", models.BooleanField(default=False)),
                ("placed_date", models.DateField(blank=True, null=True)),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage score 0-100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "exam_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("ABSENT", "Absent"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "final_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "final_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_attendance_hours", models.IntegerField(blank=True, null=True)),
                ("attendance_hours", models.IntegerField(blank=True, null=True)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.centre",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "is_enrolled",
                            "is_trained",
                            "is_certified",
                            "is_placed",
                        ],
                        name="core_enroll_is_enro_f38c7d_idx",
                    ),
                    models.Index(
                        fields=["batch_name"], name="core_enroll_batch_n_6fc14a_idx"
                    ),
                    models.Index(
                        fields=["centre", "course"],
                        name="core_enroll_centre__8b746d_idx",
                    ),
                ],
                "unique_together": {("student", "course")},
            },
        ),
    ]
