# Generated by Django 5.2.13 on 2026-04-18 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="centre",
            name="centre_admin",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "centreadmin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_centre",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
