# Generated by Django 5.2.13 on 2026-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="batch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("COMPLETED", "Completed"),
                    ("UPCOMING", "Upcoming"),
                    ("CANCELLED", "Cancelled"),
                    ("HOLD", "Hold"),
                ],
                default="ACTIVE",
                max_length=200,
                null=True,
            ),
        ),
    ]
