# Generated by Django 5.2.13 on 2026-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_centre_centre_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="custom_batch_name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
